config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :email_submissions do
      get "/upvote", to:"vote#up_vote"
      get "/downvote", to:"vote#down_vote"
    end

  root 'email_submissions#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_submission.rb
class EmailSubmission < ApplicationRecord
  belongs_to :user
  has_many :votes
  def up_votes
    votes.where(value: 1).count
  end
  def down_votes
    votes.where(value: -1).count
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
   :confirmable # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :email_submissions
    has_many :votes
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :email_submission, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/email_submissions_controller.rb
class EmailSubmissionsController < ApplicationController

  def new
  end

  def create
    @email_submission= EmailSubmission.new(email_submission_params)
    @email_submission.user = current_user
    @email_submission.save
    redirect_to @email_submission
  end

  def post
  end

  def show
    @email_submission = EmailSubmission.find(params[:id])
  end

  def index
    @email_submissions = EmailSubmission.all
  end

  def destroy
    @email_submission = EmailSubmission.find(params[:id])
    if @email_submission.user == current_user
      @email_submission.destroy
    end
    redirect_to new_email_submission_path
     #authorize @email_submission

=begin
    if @email_submission.destroy
       flash[:notice] = "\"#{@email_submission.title}\" was deleted successfully."
       redirect_to new_email_submission_path
     else
       flash[:error] = "There was an error deleting."
       render :show
     end
=end
  end

  private

  def email_submission_params
    params.require(:email_submission).permit(:title, :text)
  end

end

app/controllers/vote_controller.rb
class VoteController < ApplicationController
  def up_vote
    if current_user.votes.where(email_submission: params[:email_submission_id]).empty?
      @vote = Vote.new
      @vote.email_submission = EmailSubmission.find(params[:email_submission_id])
      @vote.user = current_user
      @vote.value = 1
      @vote.save
    end
    redirect_to :back
  end
  def down_vote
    if current_user.votes.where(email_submission: params[:email_submission_id]).empty?
      @vote = Vote.new
      @vote.email_submission = EmailSubmission.find(params[:email_submission_id])
      @vote.user = current_user
      @vote.value = -1
      @vote.save
    end
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_name
    "Kandis"
  end
end

app/helpers/email_submission_helper.rb
module EmailSubmissionHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/email_submissions/index.html.erb
<h1>All Emails</h1>
<% @email_submissions.each do |email| %>
  <p><%= link_to email.title, email.text %></p>
  <small>
     submitted <%= time_ago_in_words(email.created_at) %> ago by <%= email %><br>
  </small>
  <%= render partial: 'vote/voter', locals: { email: email } %>
  <% if email.user == current_user %>
    <%= link_to "Delete Email Submission", email_submission_path(email), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this submission?' } %>
  <% end%>

<% end %>
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>
<li><%= link_to "Create New Post", new_email_submission_path %></li>

app/views/email_submissions/new.html.erb
<%= form_for EmailSubmission.new do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<li><%= link_to "Show All Submissions", email_submissions_path %></li>

app/views/email_submissions/show.html.erb
Email Submission

<%= link_to @email_submission.title, @email_submission.text %></p>

<li><%= link_to "Show All Submissions", email_submissions_path %></li>
<li><%= link_to "Create New Post", new_email_submission_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Email</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/vote/_voter.html.erb
<%= link_to " ", email_submission_upvote_path(email), class: 'glyphicon glyphicon-chevron-up' %>
<strong><%= email.up_votes %></strong>
<%= link_to " ", email_submission_downvote_path(email), class: 'glyphicon glyphicon-chevron-down' %>
<strong><%= email.down_votes %></strong>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
 <p>Created by:<%=my_name%> </p>
<ul>
     <li><%= link_to "Home", email_submissions_path %></li>
     <li><%= link_to "Submit", email_submissions_path %></li>
</ul>

<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>